module.exports = {
  add: require("./add"),
  addRemote: require("./addRemote"),
  canFetchRemote: require("./canFetchRemote"),
  commit: require("./commit"),
  fetch: require("./fetch"),
  getRemoteUrl: require("./getRemoteUrl"),
  getCurrentCommitOid: require("./getCurrentCommitOid"),
  init: require("./init"),
  isSupported: require("./isSupported"),
  merge: require("./merge"),
  push: require("./push"),
  somethingToCommit: require("./somethingToCommit"),
  updateServerInfo: require("./updateServerInfo"),
};
